# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  photogallery:
    image: photogallery
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8089:8089
